### ISSUE TITLE
Combined BUG / regression issues that need attention and response.

### ISSUE THREAD

**Issue by ToddCrimson** [element-hq/element-android#8988]
### Steps to reproduce

Dear element-android devs. There are some very key critical bugs and regression that have been introduced in your latest builds, reported all over the issues, but there hasn't been a single response from any dev on those issues. I implore you to please provide a response. Any response would be helpful. I see that you are active here, since you just posted a release on 1.6.28, but that post has no mention of addressing the existing regressions.

1. Ver 1.6.20 introduced the Microphone bug, detailed in this issue log many times. Brief summary: If the focus from active app is shifted, the microphone access went away.
2. Ver 1.6.22 introduced the App Crash bug, also detailed many times. Where if you your device is screen locked, and anyone else calls you on element, the app crashes within a second. You may receive half a bell.
3. Ver 1.6.24 fixed the Microphone bug, but kept the device sceen locked, crash bug.
4. Ver 1.6.26 continued with the crash bug when screen locked, but also introduced another regression, where Microphone access will not be given back to OS, even when the call ended. 

The crash is causing the app to be very much non-usable in use cases where users are not just chatting but also doing audio / video calls. There are other issues reported as well, which are buggy, but this one is very critical.

Right now, on Android, your latest releases are no usable to receive calls. (We haven't tested it on iOS). 
The only way we can make our use case work is to continue to using ver 1.6.18., but that version doesn't have support for authenticated media, so we have to turn that off on our synapse matrix server.

I can see that you have now made release announcement for version 1.6.28, but have no clue what that release is going to address or fix. 

I understand that element is busy releasing element X, but that app doesn't yet fully replace element-android functionality and we are dependent on a functioning element-android app. 

Could one of you devs (@bmarty , @BillCarsonFr , @ouchadam , @ganfra , @onurays , @Florian14 , @ericdicanin) or any representative of element please provide clarity and an answer?

I know that a lot of us would benefit from clarity, intent and timeline if any.

Thank you.

### Outcome

Expect a response and timeline for the regressions that have been introduced.

### Your phone model

Pixel 8 Pro, Pixel 7 A, Pixel 9

### Operating system version

Android 14 and 15

### Application version and app store

Element version 1.6.20, 1.6.22, 1.6.24 and 1.6.26

### Homeserver

Synapse 1.121.1 (2024-12-11)

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ToddCrimson** [comment]
some action on the crashing part here: https://github.com/element-hq/element-android/issues/8964#issuecomment-2587690144

and a PR here: https://github.com/element-hq/element-android/pull/8989#issue-2784652116

Thank you @christianrowlands for your efforts on this.

**Comment by ToddCrimson** [comment]
What's going on here?

![Screenshot_20250113_113502](https://github.com/user-attachments/assets/8626b5f0-c82b-4e9b-a7f9-25e253dff0c7)

**Comment by KeithCavill** [comment]
This sound fascinating. Has this project been completely abandoned by the original developers?
Looks like for past 6 months all merges to main are failing and the developer(s) neither seem to care nor do they respond officially to any of these bug reports. 
I was hoping to start using this project for our work.

**Comment by atuctuc** [comment]
i just installer the version 1.6.28 from fdroid on my samsung A40 and there is still the same bug. it cashes when in background and an call coms in.

**Comment by christianrowlands** [comment]
@KeithCavill , I don't think the developers have abandoned this project, I just think they are heavily focused on the replacement app, [ElementX](https://github.com/element-hq/element-x-android). If I understand correctly, that app will replace the old Element Android app, and development on it has been harder than previously expected so it is eating up more developer time (I could be wrong here, but that is my impression). From time to time the developers come back and do small tasks on this app, but overall they are trying to sunset it so that everyone can move to the new ElementX app.

That being said, I am not affiliated with this project, I have just fixed a few small bugs that needed to be addressed, one of them is the incoming call crash bug. Benoit is in the process of reviewing my fix for that bug, so hopefully it comes out in the next release: https://github.com/element-hq/element-android/pull/8989

**Comment by ToddCrimson** [comment]
Hi @christianrowlands , I saw your efforts on this, and I think along with me everyone appreciates it. Also, I echo your comment that they (devs) are probably busy with element-x. 

Having said that: I do think they have should respond and they should release a working version, since element-x is beta at its best. Missing a lot of functionality which everyone here is used to. Their inaction for last 6 months, does cause concern. This app element-android was a fully functional Matrix client which, works for most use cases. Releasing a non working version for last 5 releases is not the right approach, and then ignoring the submission of critical crash errors is frustrating. So I also echo Keith's concern about perceived abandonment of this project. 

Regarding the actual critical bug: I was reading your responses on the pull request with Marty.
Just want to make sure that the use case that you are targeting to solve, will solve all the issues related to that critical bug.

1. If recipient device is locked, and someone else calls the user on that device (video or audio - BOTH), the app rings with half a ring, and then immediately crashes. I believe you discovered, that it might have to do with microphone access. Just pointing out as it happens on both audio and video calls.
2. If recipient device is unlocked, and the app is in front, and it receives an incoming call, it rings properly and you can answer, but after hanging up, the "microphone" access is not released back to the OS. It shows on top with an icon that the microphone access is still being accessed, unless you force stop / kill the app and then restart the app. (this is happening in at least version 1.6.26. I haven't been able to check 1.6.28 as it is not yet on F-Droid. 

Once again, thank you for your help on this.

**Comment by christianrowlands** [comment]
@ToddCrimson , I agree as well. To give confidence in Element Android, as well as ElementX, the maintainers need to address critical bugs as they come up. Given the state of ElementX being half baked, and Element Android having its quality starting to slip, I am starting to lose confidence myself, but I also understand how software development goes when there are limited developer resources. It is challenging to say the least.

As for the items you called out:

1. Yes, I fixed this bug in my PR.
2. I did not specifically fix this bug, but I just tested it on a Pixel 8 Pro running Android 15 and the microphone was released correctly. I am guessing a different commit fixed the issue, but it seems to be resolved now (at least for me)

**Comment by ToddCrimson** [comment]
@christianrowlands , you are awesome !! Thank you. I wish I knew code development. I think I should start self teaching. 
I have the exact same Pixel 8 Pro running Android 15. 

So I'm assuming you were able to get an apk with this fix in the PR.
Any chance you can share the apk? 
Also, since all our phones (my team here) are non-google Pixel phones, we need the version that comes from F-Droid (which allows background sync). We tried with gplay versions, but they seem to only have GCM in them. 

Anyways, if you can share your apk, great, I can atleast test it as well.
if not, no worries, we'll just wait for the fix

**Comment by christianrowlands** [comment]
Yep, I can share the apk. Message me on Element [at]craxiom:matrix.org , or Signal craxiom.13 and I will send the apk.

It takes some effort, but learning to code is not super hard if you have a structured, problem solving mindset. It is worth taking a stab at it if you are interested.

**Comment by ToddCrimson** [comment]
Thanks, sent you a dm on element

**Comment by atuctuc** [comment]
could you please post a link to download a functioning apk here?

**Comment by ToddCrimson** [comment]
Scroll to the bottom of this page:

**Comment by atuctuc** [comment]
> [@atuctuc](https://github.com/atuctuc) , Scroll to the bottom of this page: You'll see three APKs. Choose the one that you need - Gplay vs FDroid. The FDroid version allows background sync or ntfy, without using Google cloud messaging.
> 
> https://github.com/element-hq/element-android/actions/runs/12871671822

thanks for the link. i see this at the end of the page i see:

![Image](https://github.com/user-attachments/assets/97ab9042-2162-4fd8-981f-c0b3fdece853)

but i cant download any apk here?

**Comment by atuctuc** [comment]
a sorry, i have be logged into github

**Comment by ToddCrimson** [comment]
Ahh, yes, you must be logged into github :)

**Comment by atuctuc** [comment]
i tried to install vector-fdroid-arm64-v8a-debug.apk on my samsung A40. the installer rund and then it says:

Element - dbg
App wurde nicht installiert

strange?

**Comment by ToddCrimson** [comment]
@atuctuc, couple of things:

1. You have to make sure to allow for the source you are installing from. So if it is the file manager, allow from there. If it was direct browser, allow from there. 
2. It will be a second app, as Element - dbg, since it is a debug version, not release version.

Can you try installing again, with allowed source, and then check logs? if that continues to happen, try to install over adb via USB debugging from your computer.

**Comment by AltruisticRambler** [comment]
Hi everyone! Just wanted to chime in and say I agree along with what Todd & Cristian have been saying - I am very excited for Element X to reach a more stable state, but it's not quite there yet! Understandable to focus efforts toward the new thing, but this background crash bug has been around for quite some time and is very impactful to the usability of the app!! 

Big thanks to @christianrowlands for the fix (hope it gets merged soon ! 😁🤞). Good luck on your programming journey, @ToddCrimson! 🙂🤘

**Comment by ToddCrimson** [comment]
@christianrowlands, wanted to give you a quick update.

Installed the debug version from here and installed the build version you provided. (both apk files)

Both of them were the F-Droid version. 
With both tried background sync and ntfy.
Both crashed, when device was locked with an incoming call. (audio or video)

Call rings for literally half a second, and then app crashes.
Unlock the phone, open app, brings up the dialog box that app crashed.

So, something is still not working here. I tried this on:
1. Pixel 8 Pro running latest Google Stock - (This is our test phone, we don't use that for day to day things, as we are trying not to use google services)
2. Pixel 7 running latest GrapheneOS
3. Pixel 8 running latest LineageOS

So switched back to 1.6.18, and it is working again.

Wanted to make you aware, that the patched version is still crashing.

**Comment by christianrowlands** [comment]
Thanks for the update, and thanks for testing it. Strange that it works on my Pixel 8 Pro running Android 15. Must be something I missed. I will DM you for the crash logs.

**Comment by AltruisticRambler** [comment]
I'd love to test it & send logs too... but despite being logged in, I am not seeing the apk! 🤔 Checked while logged in on mobile & desktop; I just see the same list that atuctuc sent before=

> ![Image](https://github.com/user-attachments/assets/97ab9042-2162-4fd8-981f-c0b3fdece853)

Sorry to be cluttering this thread!

**Comment by atuctuc** [comment]
on the the A40 i could not install becaus it only allows signd apk's:
adb install vector-fdroid-arm64-v8a-debug.apk
Performing Streamed Install
adb: failed to install vector-fdroid-arm64-v8a-debug.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1926054728.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1926054728.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]


i teste on my rooted xiaomi 11 Lite 5GNE and here seemes to worke without crahes !!! great thanks !!!

**Comment by christianrowlands** [comment]
@AltruisticRambler Either of the `vector-Fdroid-debug` or `vector-Gplay-debug` items should work. Those are zip files that contain multiple APKs in them. Do you see the download link on the right side?

![Image](https://github.com/user-attachments/assets/12621377-47dd-4820-82be-b11fa2271ac5)

**Comment by christianrowlands** [comment]
> [@christianrowlands](https://github.com/christianrowlands), wanted to give you a quick update.
> 
> Installed the debug version from here and installed the build version you provided. (both apk files)
> 
> Both of them were the F-Droid version. With both tried background sync and ntfy. Both crashed, when device was locked with an incoming call. (audio or video)
> 
> Call rings for literally half a second, and then app crashes. Unlock the phone, open app, brings up the dialog box that app crashed.
> 
> So, something is still not working here. I tried this on:
> 
> 1. Pixel 8 Pro running latest Google Stock - (This is our test phone, we don't use that for day to day things, as we are trying not to use google services)
> 2. Pixel 7 running latest GrapheneOS
> 3. Pixel 8 running latest LineageOS
> 
> So switched back to 1.6.18, and it is working again.
> 
> Wanted to make you aware, that the patched version is still crashing.

@ToddCrimson and I debugged this and we were able to get it working. Still not 100% sure what was going on, but I sent him a new APK with some extra logging and it worked. I am guessing I built the first APK I sent him incorrectly (maybe from the wrong branch or something). Either way, it is working now.

**Comment by ToddCrimson** [comment]
> on the the A40 i could not install becaus it only allows signed apk's: adb install vector-fdroid-arm64-v8a-debug.apk Performing Streamed Install adb: failed to install vector-fdroid-arm64-v8a-debug.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1926054728.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1926054728.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]
> 
> i teste on my rooted xiaomi 11 Lite 5GNE and here it seemes to worke without crahes !!! great thanks!!!
> 
> also an annoying old bug seems to be fixed now, on my xiaomi only lock screen appeared on incoming call, now i see the call buttons

@atuctuc - Ok so on your A40, maybe try this:

1. Push this specific apk into the downloads folder --- adb push /<filepath>/<filename> /sdcard/Download
2. Now go to Google Play store, and somewhere there in Google Play Store is a setting to turn off APP checking. I forget what that option is exactly, but there is an option somewhere in the store which puts that check mark, where the play store is checking every single app installed on your device.
3. Now use your local file manager (try using a third party file manager, just to be sure, instead of google's version, but I think even google's version should be ok, but I'm trying to eliminate if google is causing issues)
4. Then browse to your Downloads folder, and click on that file. It will probably ask, what do you want to use to install the file or may ask that this app is not allowed to install... If former, then use the inbuilt package manager, if latter, allow the app.

If even now it fails, can you share that screenshot. I'll try to help you debug it.

**Comment by ToddCrimson** [comment]
> > [@christianrowlands](https://github.com/christianrowlands), wanted to give you a quick update.
> > Installed the debug version from here and installed the build version you provided. (both apk files)
> > Both of them were the F-Droid version. With both tried background sync and ntfy. Both crashed, when device was locked with an incoming call. (audio or video)
> > Call rings for literally half a second, and then app crashes. Unlock the phone, open app, brings up the dialog box that app crashed.
> > So, something is still not working here. I tried this on:
> > 
> > 1. Pixel 8 Pro running latest Google Stock - (This is our test phone, we don't use that for day to day things, as we are trying not to use google services)
> > 2. Pixel 7 running latest GrapheneOS
> > 3. Pixel 8 running latest LineageOS
> > 
> > So switched back to 1.6.18, and it is working again.
> > Wanted to make you aware, that the patched version is still crashing.
> 
> [@ToddCrimson](https://github.com/ToddCrimson) and I debugged this and we were able to get it working. Still not 100% sure what was going on, but I sent him a new APK with some extra logging and it worked. I am guessing I built the first APK I sent him incorrectly (maybe from the wrong branch or something). Either way, it is working now.

@christianrowlands  - Confirming that we both tested and debugged both of the latest versions / commits. They are both working - The crash issues is going - Tested it on all three of the devices above with different ROMs, including the stock ROM. 

@bmarty, Hoping to see the this merged into the new release version soon.

Also a question for you @bmarty -- Any chance you can (if you don't mind) start placing the F-Droid releases in your releases as well? Not just the gplay versions? As there is a very significant delay before it actually appears on F-Droid side. 

Thanks.

**Comment by ToddCrimson** [comment]
@christianrowlands, just FYI: In the past two days, I've still had a few intermittent crashes on incoming calls. Same Fatal Exception. Sending you the logs.

**Comment by ToddCrimson** [comment]
[Element - dbg log - Fatal Exception.txt](https://github.com/user-attachments/files/18546887/Element.-.dbg.log.-.Fatal.Exception.txt)

**Comment by AltruisticRambler** [comment]
> [@AltruisticRambler](https://github.com/AltruisticRambler), let me know if you can see the download links. 

Sorry, just saw this! I see - didn't realize the apks are part of the zips. I'll download and start testing now! 🙂👍

**Comment by KeithCavill** [comment]
@ToddCrimson and @christianrowlands 

confirming that it is continuing to crash. 
desperately looking for the devs here to fix this android and ios version.
both are broken.

**Comment by christianrowlands** [comment]
With @ToddCrimson 's help (thanks for running it and sending the logs), I was able to identify what was causing the crash. I have updated PR https://github.com/element-hq/element-android/pull/8989 and believe the the problem has been resolved. I just need someone from the Element dev team to review my PR so we can get it merged.

@KeithCavill , I would appreciate it if you ran with the latest APK from the PR to see if the latest commit fixed the issue.

**Comment by AltruisticRambler** [comment]
Interesting - I've been running the dbg-fdroid build since last I posted (around 6 days) & have received a few (3-4) calls without any issue! I'll stick on this build for a bit just to see if I can catch a crash! :) cheers, ya'll!

**Comment by christianrowlands** [comment]
Thanks for testing @AltruisticRambler !

@bmarty , I think the PR is ready to merge: https://github.com/element-hq/element-android/pull/8989

**Comment by christianrowlands** [comment]
The fix for the incoming call crash has been merged! Thanks @bmarty !

I believe that all the four items from this issue has been resolved. @ToddCrimson , once the release is pushed out can you confirm that all four items have been resolved? FYI, I was never able to reproduce # 4, so I need you to confirm it has been fixed.

**Comment by ToddCrimson** [comment]
Thanks @christianrowlands, this has been very helpful.

**Update on f-droid version:**

Confirming that tests across three devices, worked with the following caveat:

1. If you install the app ntfy on your android for push notifications, and the app is enabled, we noticed some random crashes.
2. On the other hand if you completely disable and or remove ntfy app, and just use "background sync", 3 days of testing, 33 incoming calls, and no crash, so bravo.. it works. Thank you.

I think that null check really helped. So for now if we use background sync (which can be delayed at times), everything works just fine.

**the iOS version**

This is continuing to crash unfortunately. And I'm not an expert, but it seems impossible to go to prior version without doing crazy hacks on iOS. I'm hoping the lessons learnt from this code fix can be applied to iOS version too.

Lastly:

Request to actual element Devs here ==> Please do keep a stable running version for both the platforms, and imploring you to please don't sacrifice element-android and element-ios for element-x as that app is not ready for primetime yet.

Thanks

**Comment by KeithCavill** [comment]
Hello everyone. Christian I have been testing the fdroid version since last night as it just got posted there. It works perfectly as Todd said without ntfy. I haven't seen any crashes on my Android anymore. Thank you !!! (can't believe the element dev team officially haven't said anything on this thread)

I would like to however point out that the ios version is still crashing, and would echo same comments as above.

Can the devs please do something? @bmarty ?

**Comment by AltruisticRambler** [comment]
Again, sorry to clutter this thread - quick question! I saw that the fix was merged into the development branch, but I'm not familiar enough with github to track down whether this fix has made it to the master release branch yet?

I've been hanging out on the debug build to guarantee I can get calls... But it's a bit slow! I would love to go back to the proper release build, if the fix has made it there! 🙂

**Comment by christianrowlands** [comment]
The released version 1.6.30 has the incoming call fix, so you are good to switch to a release build.

**Comment by ToddCrimson** [comment]
@AltruisticRambler, confirming that we have been using 1.6.30 and it works without issues.

**Comment by bmarty** [comment]
Thanks. Let's close this issue!
